-- ============================================================
-- PMS Activity Fields Migration - Oracle
-- Version: v2 (Activity 統一管理欄位)
-- Tables: PMS_PROJECTS, PMS_PROJECT_PHASE_GATES, PMS_TASKS
-- Note: Spring Boot ddl-auto:update will handle most of these
--       automatically. This script is for manual DBA reference.
-- ============================================================

-- ── PMS_PROJECTS ────────────────────────────────────────────
-- (Most fields already exist; only add if missing)

ALTER TABLE PMS_PROJECTS ADD (ACTIVITY_TYPE VARCHAR2(20) DEFAULT 'PROJECT');
ALTER TABLE PMS_PROJECTS ADD (OWNER_ID NUMBER(19,0));
ALTER TABLE PMS_PROJECTS ADD (RESPONSIBLE_ROLES VARCHAR2(500));
ALTER TABLE PMS_PROJECTS ADD (PLANNED_DURATION VARCHAR2(50));
ALTER TABLE PMS_PROJECTS ADD (ACTUAL_START_DATE VARCHAR2(50));
ALTER TABLE PMS_PROJECTS ADD (ACTUAL_END_DATE VARCHAR2(50));
ALTER TABLE PMS_PROJECTS ADD (ACTUAL_DURATION VARCHAR2(50));
ALTER TABLE PMS_PROJECTS ADD (BPM_USER_ID NUMBER(19,0));
ALTER TABLE PMS_PROJECTS ADD (MIPM_USER_ID NUMBER(19,0));
ALTER TABLE PMS_PROJECTS ADD (SQE_USER_ID NUMBER(19,0));
ALTER TABLE PMS_PROJECTS ADD (ENG_USER_ID NUMBER(19,0));
ALTER TABLE PMS_PROJECTS ADD (PUR_USER_ID NUMBER(19,0));
ALTER TABLE PMS_PROJECTS ADD (DQA_USER_ID NUMBER(19,0));
ALTER TABLE PMS_PROJECTS ADD (ERD_USER_ID NUMBER(19,0));

-- ── PMS_PROJECT_PHASE_GATES ─────────────────────────────────
ALTER TABLE PMS_PROJECT_PHASE_GATES ADD (ACTIVITY_TYPE VARCHAR2(20) DEFAULT 'PHASE');
ALTER TABLE PMS_PROJECT_PHASE_GATES ADD (OWNER_ID NUMBER(19,0));
ALTER TABLE PMS_PROJECT_PHASE_GATES ADD (RESPONSIBLE_ROLES VARCHAR2(500));
ALTER TABLE PMS_PROJECT_PHASE_GATES ADD (PLANNED_START_DATE VARCHAR2(50));
ALTER TABLE PMS_PROJECT_PHASE_GATES ADD (PLANNED_END_DATE VARCHAR2(50));
ALTER TABLE PMS_PROJECT_PHASE_GATES ADD (PLANNED_DURATION VARCHAR2(50));
ALTER TABLE PMS_PROJECT_PHASE_GATES ADD (ACTUAL_START_DATE VARCHAR2(50));
ALTER TABLE PMS_PROJECT_PHASE_GATES ADD (ACTUAL_END_DATE VARCHAR2(50));
ALTER TABLE PMS_PROJECT_PHASE_GATES ADD (ACTUAL_DURATION VARCHAR2(50));

-- ── PMS_TASKS ────────────────────────────────────────────────
ALTER TABLE PMS_TASKS ADD (ACTIVITY_TYPE VARCHAR2(20) DEFAULT 'TASK');
ALTER TABLE PMS_TASKS ADD (OWNER_ID NUMBER(19,0));
ALTER TABLE PMS_TASKS ADD (RESPONSIBLE_ROLES VARCHAR2(500));
ALTER TABLE PMS_TASKS ADD (PLANNED_DURATION VARCHAR2(50));
ALTER TABLE PMS_TASKS ADD (ACTUAL_DURATION VARCHAR2(50));

-- ── PMS_RESPONSIBLE_ROLES ────────────────────────────────────
-- Default seed data (BPM, MIPM, SQE, ENG, PUR, DQA, ERD)
INSERT INTO PMS_RESPONSIBLE_ROLES (ROLE_NAME) SELECT 'BPM'  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PMS_RESPONSIBLE_ROLES WHERE ROLE_NAME='BPM');
INSERT INTO PMS_RESPONSIBLE_ROLES (ROLE_NAME) SELECT 'MIPM' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PMS_RESPONSIBLE_ROLES WHERE ROLE_NAME='MIPM');
INSERT INTO PMS_RESPONSIBLE_ROLES (ROLE_NAME) SELECT 'SQE'  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PMS_RESPONSIBLE_ROLES WHERE ROLE_NAME='SQE');
INSERT INTO PMS_RESPONSIBLE_ROLES (ROLE_NAME) SELECT 'ENG'  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PMS_RESPONSIBLE_ROLES WHERE ROLE_NAME='ENG');
INSERT INTO PMS_RESPONSIBLE_ROLES (ROLE_NAME) SELECT 'PUR'  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PMS_RESPONSIBLE_ROLES WHERE ROLE_NAME='PUR');
INSERT INTO PMS_RESPONSIBLE_ROLES (ROLE_NAME) SELECT 'DQA'  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PMS_RESPONSIBLE_ROLES WHERE ROLE_NAME='DQA');
INSERT INTO PMS_RESPONSIBLE_ROLES (ROLE_NAME) SELECT 'ERD'  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PMS_RESPONSIBLE_ROLES WHERE ROLE_NAME='ERD');

COMMIT;
