-- =============================================================================
-- PMS v5: Deliverable Management Schema (Oracle 12c+)
-- Date: 2026-04-22
-- Description: Adds Deliverable Type, Workflow, Deliverable, and linking tables
-- Requires Oracle 12c+ (uses GENERATED BY DEFAULT AS IDENTITY)
-- Run once against the Oracle schema. Safe to re-run: each block skips if
-- the object already exists (ORA-00955 / ORA-01408 are silently ignored).
-- =============================================================================

-- 1. Deliverable Types
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE pms_deliverable_types (
      id          NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name        VARCHAR2(100) NOT NULL,
      description VARCHAR2(500),
      created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2. Custom field definitions per Deliverable Type
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE pms_deliverable_type_fields (
      id           NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      type_id      NUMBER(19,0) NOT NULL
                     REFERENCES pms_deliverable_types(id) ON DELETE CASCADE,
      field_name   VARCHAR2(100) NOT NULL,
      field_type   VARCHAR2(20)  DEFAULT ''TEXT'' NOT NULL,
      field_options CLOB,
      field_order  NUMBER(10,0)  DEFAULT 0
    )';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 3. Workflow templates
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE pms_workflows (
      id          NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name        VARCHAR2(100) NOT NULL,
      description VARCHAR2(500),
      created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 4. Workflow steps
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE pms_workflow_steps (
      id          NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      workflow_id NUMBER(19,0) NOT NULL
                    REFERENCES pms_workflows(id) ON DELETE CASCADE,
      step_name   VARCHAR2(100) NOT NULL,
      step_order  NUMBER(10,0)  DEFAULT 1 NOT NULL,
      description VARCHAR2(500)
    )';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 5. Deliverable master table
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE pms_deliverables (
      id          NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name        VARCHAR2(200) NOT NULL,
      type_id     NUMBER(19,0)  REFERENCES pms_deliverable_types(id) ON DELETE SET NULL,
      description CLOB,
      created_by  NUMBER(19,0),
      created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 6. Custom field values per deliverable
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE pms_deliverable_field_values (
      id             NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      deliverable_id NUMBER(19,0) NOT NULL
                       REFERENCES pms_deliverables(id) ON DELETE CASCADE,
      field_def_id   NUMBER(19,0) NOT NULL
                       REFERENCES pms_deliverable_type_fields(id) ON DELETE CASCADE,
      field_value    CLOB,
      CONSTRAINT uq_del_field_value UNIQUE (deliverable_id, field_def_id)
    )';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 7. Activity <-> Deliverable many-to-many
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE pms_activity_deliverables (
      id             NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      target_type    VARCHAR2(20)  NOT NULL,
      target_id      VARCHAR2(100) NOT NULL,
      deliverable_id NUMBER(19,0)  NOT NULL
                       REFERENCES pms_deliverables(id) ON DELETE CASCADE,
      created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT uq_activity_deliverable UNIQUE (target_type, target_id, deliverable_id)
    )';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 8. Deliverable <-> Workflow with step progress
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE pms_deliverable_workflows (
      id              NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      deliverable_id  NUMBER(19,0) NOT NULL
                        REFERENCES pms_deliverables(id) ON DELETE CASCADE,
      workflow_id     NUMBER(19,0) NOT NULL
                        REFERENCES pms_workflows(id) ON DELETE CASCADE,
      current_step_id NUMBER(19,0) REFERENCES pms_workflow_steps(id) ON DELETE SET NULL,
      started_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT uq_deliverable_workflow UNIQUE (deliverable_id, workflow_id)
    )';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 9. Workflow step audit log
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE pms_deliverable_workflow_log (
      id                      NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      deliverable_workflow_id NUMBER(19,0) NOT NULL
                                REFERENCES pms_deliverable_workflows(id) ON DELETE CASCADE,
      step_id                 NUMBER(19,0) REFERENCES pms_workflow_steps(id) ON DELETE SET NULL,
      action                  VARCHAR2(20)   NOT NULL,
      action_by               NUMBER(19,0),
      action_at               TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      comments                VARCHAR2(1000)
    )';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- =============================================================================
-- Indexes (skipped if already exist: ORA-01408)
-- =============================================================================
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_del_type_fields_type_id ON pms_deliverable_type_fields(type_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 AND SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_wf_steps_workflow_id ON pms_workflow_steps(workflow_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 AND SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_deliverables_type_id ON pms_deliverables(type_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 AND SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_del_field_vals_del_id ON pms_deliverable_field_values(deliverable_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 AND SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_activity_del_target ON pms_activity_deliverables(target_type, target_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 AND SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_activity_del_del_id ON pms_activity_deliverables(deliverable_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 AND SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_del_workflows_del_id ON pms_deliverable_workflows(deliverable_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 AND SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_del_workflows_wf_id ON pms_deliverable_workflows(workflow_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 AND SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_del_wf_log_dwf_id ON pms_deliverable_workflow_log(deliverable_workflow_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 AND SQLCODE != -955 THEN RAISE; END IF; END;
/
