-- PMS v6: Activity Teams (Oracle 12c+)
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE pms_activity_teams (
      id             NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      target_type    VARCHAR2(20)  NOT NULL,
      target_id      VARCHAR2(100) NOT NULL,
      user_id        NUMBER(19,0)  NOT NULL,
      responsibility VARCHAR2(20)  DEFAULT ''Member'' NOT NULL,
      created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT uq_activity_team UNIQUE (target_type, target_id, user_id)
    )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_activity_teams_target ON pms_activity_teams(target_type, target_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 AND SQLCODE != -955 THEN RAISE; END IF;
END;
/
