spring:
  application:
    name: pms-system
  config:
    import: "optional:file:D:/agile_config/pms/application_pms.yml"

---
spring:
  config:
    activate:
      on-profile: "oracle"
    import: "optional:file:D:/agile_config/pms/application-oracle_pms.yml"

---
spring:
  config:
    activate:
      on-profile: "postgresql"
    import: "optional:file:D:/agile_config/pms/application-postgresql_pms.yml"
